pod 'SnapKit'
pod 'SQLite.swift', '~> 0.10.1'
pod 'Alamofire'
pod 'MBProgressHUD'
pod 'SwiftyJSON'
pod 'Ji'
pod 'AlamofireImage'
pod 'SwiftQRCode'
pod "ESPullToRefresh"
pod 'UMengAnalytics-NO-IDFA'

use_frameworks!
