pod 'SnapKit'
pod 'SQLite.swift', '~> 0.10.1'
pod 'Alamofire'
pod 'SwiftyJSON'
pod 'Ji'
pod 'AlamofireImage'
pod 'SwiftQRCode'
pod "ESPullToRefresh"
pod 'UMengAnalytics-NO-IDFA'
pod 'UMengSocialCOM', '~> 5.2.1'


use_frameworks!
