pod 'SnapKit'
pod 'SQLite.swift', '~> 0.10.1'
pod 'Alamofire'
pod 'MBProgressHUD'
pod 'SwiftyJSON'
pod 'Ji'
pod 'AlamofireImage'
pod 'SwiftQRCode'
pod 'ReactiveCocoa'
pod "ESPullToRefresh"

use_frameworks!
